use_frameworks!

platform :ios, '9.0'

target 'Utils_Example' do
  pod 'Utils', :path => '../'

  target 'Utils_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
