use_frameworks!

platform :ios, '9.0'

target 'Shared_Example' do
  pod 'Shared', :path => '../'

  target 'Shared_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
