use_frameworks!

platform :ios, '9.0'

target 'PagesLinks_Example' do
  pod 'PagesLinks', :path => '../'

  target 'PagesLinks_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
