use_frameworks!

platform :ios, '9.0'

target 'MovieList_Example' do
  pod 'MovieList', :path => '../'

  target 'MovieList_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
